Fixed issue #11 allowing single line execution(updated)
NITDgpOS/manga pull request #37
Opened 2016-11-19 09:19 UTC by sark01

2016-11-19 09:22 UTC, pandusonu2 commented on downloader.sh
> +fi
Too many if else :P 
Just write one if for $manga and one if for chape and chaps. 
You are taking way too many lines

2016-11-19 09:30 UTC, pandusonu2 commented on downloader.sh
> +chape="${!d2}"
Shouldn't this be done after checking the existence of d1 and d2? 
It should be inside the if block

2016-11-19 09:31 UTC, pandusonu2 commented
Just trivial changes, please remove the ifs and correct the location of few statements. Will be mergable soon :)
Awesome PR Dude :D You killed it

2016-11-19 09:34 UTC, pandusonu2 commented on downloader.sh
> +	if [ "${!i}" = "-chap" ]; then
Since its multiple character function, please make it --chap :) Sorry I forgot about this.

2016-11-19 09:46 UTC, pandusonu2 commented on downloader.sh
> +	if [ "${!i}" = "-chap" ]; then
Since we don't have many functions to keep track of.
Keep it -c as short form and --chap as long form of command :)

2016-11-20 08:23 UTC, pandusonu2 requested changes

2016-11-20 08:23 UTC, pandusonu2 commented on downloader.sh
> +
Remove extra line

2016-11-20 08:23 UTC, pandusonu2 commented on downloader.sh
> +
Same as above

2016-11-20 08:23 UTC, pandusonu2 commented on downloader.sh
> +
Ditto

2016-11-20 08:23 UTC, pandusonu2 commented on downloader.sh
> +
Ditto

2016-11-20 08:23 UTC, pandusonu2 commented on downloader.sh
> +
Keep only one new line

2016-11-20 08:23 UTC, pandusonu2 commented on downloader.sh
> +	if [ "${!i}" = "-t" ]; then
Also make --title functions

2016-11-20 14:41 UTC, pandusonu2 commented
This PR is mergable now \\(^.^)/ Just one last thing, merge the three commits into a single commit and I will merge it :)
To do that
```
git rebase -i 1193996
```
Then when the window opens, change the starting word of line 2 and line 3 from pick->squash. Save and close it. 
You will get another window asking for your commit message for the sqaushed commit, keep it as 
"Fixed issue #11: allowing single line execution"
Save it. 
You should have just one commit then.
I'll merge the PR then.

2016-11-20 14:45 UTC, pandusonu2 approved these changes

2016-11-20 20:02 UTC, merged

2016-11-20 20:02 UTC, pandusonu2 commented
This is an amazing patch :D This takes manga to a whole new level.
Thanks a lot @sark01 for this amazing contribution.

2016-11-21 06:20 UTC, sark01 commented
Thanks @pandusonu2 , looking forward to fixing more issues in manga.