fixed #30
NITDgpOS/manga pull request #44
Opened 2016-11-22 20:00 UTC by hasan356

2016-11-22 21:11 UTC, pandusonu2 commented
Firstly, I made a new change, so your branch is behind again. Lets pull it again.
Do the following:
```
git checkout master #Goes to master branch
git pull nitDgp master #Pulls from the main branch
git checkout fix #Goes to fix branch
git rebase -i master #Rebases fix over the updated master
#Save and close the prompt that appears
git push origin fix #Pushes to your repository in github
```

2016-11-22 21:42 UTC, pandusonu2 requested changes
Ok this was little harder than I expected. Either make the changes or let me know. I will do them myself.
Do the changes AFTER you have "rebased" the branch onto updated master.(The comment before the review)
If you make changes, you have to "amend" them. 
So when you do the 
git commit, add --amend.
The command becomes ```git commit --amend```
Sorry that it got complex (-.-)" If you think its getting too complex, leave this issue and try something else, I will take care of the issue. 
Thank you for your contribution :)

2016-11-22 21:42 UTC, pandusonu2 commented on downloader.sh
> +index(){
The function should come first.

2016-11-22 21:42 UTC, pandusonu2 commented on downloader.sh
> +	local start_end="$(echo $link | grep -aob '"' | grep -oE '[0-9]+' | sed "x;d")"
Ok this is a  little bit hard I think (-.-)" Here is the function you need to write:-
```
index(){
	local start_end="$(echo $@ | grep -aob '"' | grep -oE '[0-9]+' | sed "${!#};d")"
	echo "$start_end"
}
```

2016-11-22 21:42 UTC, pandusonu2 commented on downloader.sh
> +		starti=$(index link "11q")
You are passing the arguments right.
It should be $link, so the function call becomes
```starti=$(index $link "11q")```
Apply it to all other places where it applies

2016-11-22 21:42 UTC, pandusonu2 commented on downloader.sh
> +		#starti="$(echo $link | grep -aob '"' | grep -oE '[0-9]+' | sed "11q;d")"
Don't leave stray comments in patches, please delete the line or keep it, don't comment them out.
Apply it to all other places where it applies

2016-11-23 07:20 UTC, hasan356 commented
no i will get it done :) i will make the changes

2016-11-23 17:32 UTC, pandusonu2 approved these changes

2016-11-23 17:34 UTC, pandusonu2 commented
Awesome work :D Hope you learned some things :) 
Thanks for your contribution :)
You might wanna bookmark this PR as I've explained quite a few things here. 
Feel free to check out other issues to contribute to :)

2016-11-23 17:35 UTC, merged